# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            "nobody-138"
tagline:          
description:      
url:              "https://nobody-138.github.io"
baseurl:          

